### ISSUE TITLE
4.x release

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-ui#7341]
The goal of this issue is to update React to 17.x.y and have a remote branch on this repository running on React v17.x.y without any issues. More info in pre-release article: https://swagger.io/blog/api-design/what%E2%80%99s-ahead-for-swaggerui-v4-and-swaggereditor-v4/

## Current state

We're currently running SwaggerUI on React@15.0.7 which was been released 8 months ago. React@15 release branch is more then 5 years old. It's time we start looking into what work would be required to make the update.

## Update methodology

We understand that merely updating React itself will not suffice. There is network of other libraries connected to React that need to update as well. We can use current test suite for detecting any anomalies after the React update. These anomalies needs to be documented first before we move for eliminating them. This issue will maintain a list of all anomalies that need to be eliminated along with the list of tasks that need to performed.

## Branch

All work in being done on [release/4.x](https://github.com/swagger-api/swagger-ui/tree/release/4.x) branch. [Draft PR](https://github.com/swagger-api/swagger-ui/pull/7379) has been opened as well from `release/4.x` branch.

## Community involvement

**Any community involvement is welcomed!** If you you're aware of any problem regarding usage of newer version of React then 15.0.7, please let us know in issue comments.

## Resources

- [React 16 release notes](https://reactjs.org/blog/2017/09/26/react-v16.0.html)
- [React 17 release notes](https://reactjs.org/blog/2020/10/20/react-v17.html)
- [enzyme 3.0.0 changelog](https://github.com/enzymejs/enzyme/blob/master/CHANGELOG.md#300) and [migration guide](https://github.com/enzymejs/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#migration-guide-for-enzyme-v2x-to-v3x)

## Tasks

- [x] [Update React to 17.x.y](#user-content-update-react-to-17-x-y)
- [x] [Detect and update all React related dependencies that will require update too](#user-content-detect-and-update-all-react-related-dependencies)
- [x] Detect and document all anomalies
- [x] [fix npm security vulnerabilities](#user-content-fix-npm-vulnerabilities)
- [x] [replace @kyleshockey/* libraries with original ones](#user-content-replace-kyleshockey-libaries)
- [x] update js-yaml to latest version
- [x] prefix lifecycle methods with `UNSAFE_` (1918b36b2a2cbc0e51e381cc359e389ef2420ac0)
- [x] Fix all anomalies
- [x] [don't include private IP in build](https://github.com/swagger-api/swagger-ui/issues/7446)
- [x] [update lodash to eliminate security vulnerability](https://github.com/swagger-api/swagger-ui/issues/7473)
- [x] [remove stream library](https://github.com/swagger-api/swagger-ui/issues/7499)
- [x] remove duplicates in bundle (fixed in c2044ef5169617853a453b87b3979d56a2a29f9f)
- [x] https://github.com/swagger-api/swagger-ui/issues/7477
- [x] document that it's required to use `stream-browserify` with webpack@5 (2657537929649a313f713efb0bda0969362112b1)
- [ ] https://github.com/swagger-api/swagger-ui/issues/7525
- [x] nvmrc should use Node.js 16.8 as minimum dev dep
- [x] resolve all security vulnerabilities (dismiss rest)
- [x] update husky to v7 and delete huskyrc file

### Update React to 17.x.y <a href="#user-content-update-react-to-17-x-y" id="update-react-to-17-x-y">#</a>

react and react-dom packages have been updated to v17.0.2. Console did not reported any problem. Tests immediately stopped passing.

| Updated | Name        | Used version           | Latest version |
| -----:| ------------- |:-------------:| -----:|
| &check; | [react](https://www.npmjs.com/package/react) | [15.7.0](https://www.npmjs.com/package/react/v/15.7.0) | [17.0.2](https://www.npmjs.com/package/react/v/17.0.2) |
| &check; | [react-dom](https://www.npmjs.com/package/react-dom) | [15.7.0](https://www.npmjs.com/package/react-dom/v/15.7.0) | [17.0.2](https://www.npmjs.com/package/react-dom/v/17.0.2) |

### Detect and update all React related dependencies that will require update too <a href="#user-content-detect-and-update-all-react-related-dependencies" id="detect-and-update-all-react-related-dependencies">#</a>

**Production Dependencies**

| Updated | Name        | Used version           | Latest version |
| -----:| ------------- |:-------------:| -----:|
| &check; | [react-immutable-pure-component](https://www.npmjs.com/package/react-immutable-pure-component) | [1.2.3](https://www.npmjs.com/package/react-immutable-pure-component/v/1.2.3) | [2.2.0](https://www.npmjs.com/package/react-immutable-pure-component/v/2.2.2) | 
| &check; | [react-inspector](https://www.npmjs.com/package/react-inspector) | [2.3.1](https://www.npmjs.com/package/react-inspector/v/2.3.1) | [5.1.1](https://www.npmjs.com/package/react-inspector/v/5.1.1) |
| &check; | [react-redux](https://www.npmjs.com/package/react-redux) | [4.4.10](https://www.npmjs.com/package/react-redux/v/4.4.10) | [7.2.4](https://www.npmjs.com/package/react-redux/v/7.2.4) |
| &check; | [redux](https://www.npmjs.com/package/redux) | [3.7.2](https://www.npmjs.com/package/redux/v/3.7.2) | [4.1.0](https://www.npmjs.com/package/redux/v/4.1.0) |
| &check; | [redux-immutable](https://www.npmjs.com/package/redux-immutable) | [3.1.0](https://www.npmjs.com/package/redux-immutable/v/3.1.0) | [4.0.0](https://www.npmjs.com/package/redux-immutable/v/4.0.0) |

**Development Dependencies**

| Updated | Name        | Used version           | Latest version |
| -----:| ------------- |:-------------:| -----:|
| &check; | [enzyme](https://www.npmjs.com/package/enzyme) | [2.9.1](https://www.npmjs.com/package/enzyme/v/2.9.1) | [3.11.0](https://www.npmjs.com/package/enzyme/v/3.11.0) | 
| &check; | [react-test-renderer](https://www.npmjs.com/package/react-test-renderer) | [15.7.2](https://www.npmjs.com/package/react-test-renderer/v/15.7.2) | [17.0.2](https://www.npmjs.com/package/react-test-renderer/v/17.0.2) | 

## Anomalies

- [x] [`just-test-in-node` npm script fails](#user-content-just-test-in-node-npm-script-fails)
- [x] [`test:unit-jest` npm script fails](#user-content-test-unit-jest-npm-script-fails)
- [x] [Cypress tests are failing](#user-content-cypress-tests-are-failing)
- [x] [react-inspector has different API now](#user-content-react-inspector-has-different-api-now) 
- [x] [warnings during `npm install` about non matching library versions](#user-content-npm-install-warnings)

### `just-test-in-node` npm script fails <a href="#user-content-just-test-in-node-npm-script-fails" id="just-test-in-node-npm-script-fails">#</a>

`just-test-in-node` npm script triggers errors. Current version of enzyme doesn't support react@17. In order for enzyme to work with react@17 we need to update enzyme to latest version and use [@wojtekmaj/enzyme-adapter-react-17](https://github.com/wojtekmaj/enzyme-adapter-react-17) adapter. Fixed in 6405fe725909b60aa27157c705595a7c7f141407.

### `test:unit-jest` npm script fails  <a href="#user-content-test-unit-jest-npm-script-fails" id="test-unit-jest-npm-script-fails">#</a>

Problem is with latest version of enzyme and that returns a cheerio wrapper. This is a breaking change and we have to somehow deal with it. More about this problem in https://github.com/enzymejs/enzyme/issues/1162. Related issue is that cheerio now doesn't escape quotes: `&quot;` is now interpreted as `"` by cheerio, more in https://github.com/cheeriojs/cheerio/issues/319. Empty string attributes on HTML tags are now supplied with empty string value of `""` instead of making them boolean attributes. Fixed in 3ed335ef529c94cdc8fbb1a999b43f9dd36fc949.

### Cypress tests are failing <a href="#user-content-cypress-tests-are-failing" id="cypress-tests-are-failing">#</a>

React@17 no longer support `react-addons-perf`.  Documentation says following `As of React 16, react-addons-perf is not supported. Please use your browser’s profiling tools to get insight into which components re-render.` Learn more about this problem [here](https://reactjs.org/docs/perf.html). We'll be removing `win.Perf` assign from code. Fixed in ebcd552e391acde4251db7af0cafbe6b725aeacc.

### react-inspector has different API now <a href="#user-content-react-inspector-has-different-api-now" id="react-inspector-has-different-api-now">#</a>

`initialExpandedPaths` prop on `ObjectInspector` component changed to `expandPaths`.

### warnings during `npm install` about non matching library versions <a href="#user-content-npm-install-warnings" id="npm-install-warnings">#</a>

**react-debounce-input**: requires a peer of react@^15.3.0 || ^16.0.0. Waiting for a new release witch official react@17 support without warning. Installed version 3.2.4. Ref https://github.com/nkbt/react-debounce-input/issues/137

**react-motion**: requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0. Very old not any more maintained library. The library usage was replaced by simple object in following shape: `{ stiffness: 170, damping: 26 }`

**request-promise**: request-promise@4.2.6 requires a peer of request@^2.34 but none is installed. This will go away after we uninstall `nightwatch`.

**request-promise-core**: request-promise-core@1.1.4 requires a peer of request@^2.34 but none is installed. This will go away after we uninstall `nightwatch`.

**tsutils**: tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. This will stay with us as it's transitive dependency of `eslint-plugin-jest`.  If we introduce TypeScript into codebase, it will go away.

### Fix npm security vulnerabilites <a href="#user-content-fix-npm-vulnerabilities" id="fix-npm-vulnerabilities">#</a>

All npm security vulnerabilities (except 4) has been fixed. The 4 pending vulnerabilities are comming from transitive deps of webpack@4 and cannot be easily fixed. They will go away after we update to webpack@5. For now it's completely **OK  to dismiss them** as they pose no thread. Fixed in 31626145c08e75b1d765975ca6e5616fe721e03d

### replace @kyleshockey/* libraries with original ones  <a href="#user-content-replace-kyleshockey-libaries" id="replace-kyleshockey-libaries">#</a> 

**@kyleshockey/object-assign-deep** - replaced by lodash/merge. If behavior not be compatible we'll use lodash/mergeWith.
    
**@kyleshockey/xml** - by installing `stream` library directly, we can use original xml library without the fork.

Fixed in 49c4bc4d72f645ba2d0f036486fb84aede5654dc

**Comment by tim-lai** [comment]
1. `redux` & `react-redux`
2. additional error handling to be added, to swallow production errors, e.g. `react-error-boundary`

**Comment by tim-lai** [comment]
3. deprecated UNSAFE methods
4. remaining legacy Mocha tests that should get migrated to Jest, that may be React-related

**Comment by tim-lai** [comment]
@char0n fyi, note on redux@4... existing tests don't capture certain errors that can get generated, either with user behavior or problematic definitions. Here's the PR where I reverted the redux@4 change: #6331

**Comment by char0n** [comment]
**For releasing a 4.0.0-beta.0 following changes have been made that needs to returned to original:**

**release/.release-it.json**:

Original
```json
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular"
    }
  }
```

Modified
```json
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "ignoreRecommendedBump": true
    }
  }
```

**package.json**

Original:
```json
"automated-release": "release-it -VV --config ./release/.release-it.json",
```

Modified:
```json
"automated-release": "release-it -VV major --preRelease=beta --config ./release/.release-it.json",
```

**Comment by char0n** [comment]
`.github/dependabot.yaml` has been renamed to `.github/_dependabot_.yaml`; needs to be renamed after going for v4 stable.

**Comment by char0n** [comment]
`.github/dependabot.yaml` has been renamed to `.github/_dependabot_.yaml and https://github.com/swagger-api/swagger-ui/blob/1c84fe0d6646a0d9c9f1eb3ebe299748a13021e1/.github/workflows/dependabot-merge.yml has been removed for now. (needs to be returned back after v4).

**Comment by tim-lai** [comment]
@char0n I suggest adding 2 task items:

- replace `componentWillReceiveProps` with `UNSAFE_componentWillReceiveProps` (20 instances)
- replace `componentWillMount` with `UNSAFE_componentWillMount` (1 instance)

reference [here](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

**Comment by char0n** [comment]
[Draft PR](https://github.com/swagger-api/swagger-ui/pull/7379) has been transformed into classic one.
Relase branch [release/4.x](https://github.com/swagger-api/swagger-ui/tree/release/4.x) has been rebased on top of master branch. 

Going for v4.0.0 release now.

**Comment by char0n** [comment]
Swagger-ui v4.0.0 released
