### ISSUE TITLE
SwaggerUI@v5: release first alpha version

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-ui#8403]
The goal of this issue is to release SwaggerUI@v5 first alpha version integrating latest version of swagger-client containing OpenAPI 3.1.0 implementation: https://www.npmjs.com/package/swagger-client/v/3.19.1

Existing reconfigured Jenkins pipeline will be used to issue first alpha release of SwaggerUI@v5.

**TODO:**

- [x] research and understand the changes in `next` branch
- [x] consolidate `next` branch (build system ApiDOM compensation, all tests passing)
- [x] release first V5 alpha version

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.0
