### ISSUE TITLE
OpenAPI 3.1.0 support: example generation from JSON Schema 2020-12

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-ui#8577]
The goal of this issue is to implement proper example generation for `Try it out` feature from JSON Schema 2020-12 schemas.

---

The course of action here is to amend existing `samples` plugin to work with JSON Schema 2020-12 and not to blow up. We're aiming for quick win here. If time will allow us, we want to approach JSON Schema 2020-12 -> data generation in more complex way, similar to https://github.com/json-schema-faker/json-schema-faker

---

**TODO**:

- [x] extend ability to generate data for JSON Schema 2020-12 + OpenAPI 3.1 formats ([#1](https://github.com/swagger-api/swagger-ui/pull/8882), [#2](https://github.com/swagger-api/swagger-ui/pull/8891))
- [x] [add support for `type` keyword defined as an array](https://github.com/swagger-api/swagger-ui/pull/8883)
- [x] [add support for `const` keyword](https://github.com/swagger-api/swagger-ui/pull/8884)
- [x] [amend semantics for `exclusiveMaximum` and `exclusiveMinimum` keywords](https://github.com/swagger-api/swagger-ui/pull/8885)
- [x] [add support for `multipleOf` keyword](https://github.com/swagger-api/swagger-ui/pull/8890)
- [x] [add support for `uniqueItems` keyword](https://github.com/swagger-api/swagger-ui/pull/8893) 
- [x] [add support for `contains`, `minContains` and `maxContains` keyword](https://github.com/swagger-api/swagger-ui/pull/8896)
- [x] [refactor support for `maxLength`, `minLength` and `pattern` keywords](https://github.com/swagger-api/swagger-ui/pull/8897)
- [x] [refactor support for `maxProperties`, `minProperties` and `required` keywords](https://github.com/swagger-api/swagger-ui/pull/8898)
- [x] [add support for `contentEncoding` keyword](https://github.com/swagger-api/swagger-ui/pull/8899)
- [x] [add support for `contentMediaType` keyword](https://github.com/swagger-api/swagger-ui/pull/8903)
- [x] [add support for `contentSchema` keyword](https://github.com/swagger-api/swagger-ui/pull/8907)
- [x] [separate constraints applicators for numbers and strings](https://github.com/swagger-api/swagger-ui/pull/8900)
- [x] [apply open/closed principle to plug custom encodings + media types](https://github.com/swagger-api/swagger-ui/pull/8905)
- [x] [priority order for handling `default` and `example` keyword](https://github.com/swagger-api/swagger-ui/pull/8908)
- [x] [add support for `examples` keyword](https://github.com/swagger-api/swagger-ui/pull/8908)
- [x] [add support for Boolean JSON Schema](https://github.com/swagger-api/swagger-ui/pull/8907)
- [x] [provide proper `type` keyword inference](https://github.com/swagger-api/swagger-ui/pull/8909)
- [x] [refactor merging schemas](https://github.com/swagger-api/swagger-ui/pull/8910)
- [ ] general cleanup

---

**What we'll not be adding support for (in alpha/beta phase)**:

> NOTE: the list below needs to be itemized into individual GitHub issues

- [dependentRequired keyword](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-01#section-6.5.4)
- [not keyword](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#section-10.2.1.4)
- [if keyword](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#section-10.2.2.1)
- [then keyword](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#section-10.2.2.2)
- [else keyword](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#section-10.2.2.3)
- [dependentSchemas](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-dependentschemas)
- [prefixItems](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-prefixitems)
- [patternProperties](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-patternproperties)
- [propertyNames](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-propertynames)
- [unevaluatedItems](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-unevaluateditems)
- [unevaluatedProperties](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-unevaluatedproperties)

**Comment by char0n** [comment]
Functions from `samples/fn.js` are statically imported into different modules, which makes it impossible to override. We need to first refactor the code so that `samples` plugin is used as plugin and not as static ESM module.

**Comment by char0n** [comment]
Missing keywords transformed into https://github.com/swagger-api/swagger-ui/issues/8913
