### ISSUE TITLE
Expose code related to sample generate from JSON Schema as static code

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-ui#9188]
The goal of this issue is to expose sample generation plugins from SwaggerUI in such a way so that the functionality of those plugin is accessible in static way.

**TODO**:

- [x] [consolidate SwaggerUI plugin exposure](https://github.com/swagger-api/swagger-ui/pull/9189)
- [x] [expose sample generation plugins statically](https://github.com/swagger-api/swagger-ui/pull/9190)
- [x] [create wiki page](https://github.com/swagger-api/swagger-ui/wiki/JSON-Schema-samples-API)

**Comment by char0n** [comment]
Released as  https://github.com/swagger-api/swagger-ui/releases/tag/v5.6.0
