### ISSUE TITLE
Release SwaggerUI with React@18 support

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-ui#9466]
Backward compatible React@18 support has been introduced in https://github.com/swagger-api/swagger-ui/pull/9435. The goal of this issue is to release the change and document how older versions of `React >= 16.8 <18` can still be used.

**TODO**:

- [x] [draft wiki page describing usage of older `React >= 16.8 <18` versions](https://github.com/swagger-api/swagger-ui/wiki/Using-older-version-of-React)
- [x] release SwaggerUI with React@18 support
- [x] align all integration repos in [Seamless Integration with Bundlers & Test Tools wiki page](https://github.com/swagger-api/swagger-ui/wiki/Seamless-Integration-with-Bundlers-&-Test-Tools) with new reality
- [x] release notice on Twitter & Linkedin

**Comment by char0n** [comment]
Wiki page drafted at https://github.com/swagger-api/swagger-ui/wiki/Using-older-version-of-React

**Comment by char0n** [comment]
SwaggerUI released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.11.0

**Comment by char0n** [comment]
[swagger-ui-webpack](https://github.com/char0n/swagger-ui-webpack) integration addressed in https://github.com/char0n/swagger-ui-webpack/pull/1

**Comment by char0n** [comment]
[swagger-ui-vite](https://github.com/char0n/swagger-ui-vite/pull/3) integration addressed in https://github.com/char0n/swagger-ui-vite/pull/3

**Comment by char0n** [comment]
[swagger-ui-vite-dist](https://github.com/char0n/swagger-ui-vite-dist) integration addressed in https://github.com/char0n/swagger-ui-vite-dist/pull/3

**Comment by char0n** [comment]
Parcel has in issue with certain ApiDOM code and gets confused:

![image](https://github.com/swagger-api/swagger-ui/assets/193286/1eb36f85-bfc1-44d5-ba79-d8296b5b0339)


Although the affected code is valid JavaScript, we can introduce a fix to ApiDOM consisting of not using reserved keyword as defaultly exported symbol. This should make Parcel again happy.

**Comment by char0n** [comment]
[swagger-ui-nextjs](https://github.com/char0n/swagger-ui-nextjs) integration addressed in https://github.com/char0n/swagger-ui-nextjs/pull/3

**Comment by char0n** [comment]
[swagger-ui-nextjs-typescript](https://github.com/char0n/swagger-ui-nextjs-typescript) integration addressed in https://github.com/char0n/swagger-ui-nextjs-typescript/pull/1

**Comment by char0n** [comment]
[swagger-ui-jest](https://github.com/char0n/swagger-ui-jest) integration addressed in https://github.com/char0n/swagger-ui-jest/pull/3

**Comment by char0n** [comment]
[swagger-ui-nuxt](https://github.com/char0n/swagger-ui-nuxt) integration addressed in https://github.com/char0n/swagger-ui-nuxt/pull/2

**Comment by char0n** [comment]
[swagger-ui-esbuild](https://github.com/char0n/swagger-ui-esbuild) itegration addressed in https://github.com/char0n/swagger-ui-esbuild/pull/1

**Comment by char0n** [comment]
[swagger-ui-remix](https://github.com/char0n/swagger-ui-remix) integration addressed in https://github.com/char0n/swagger-ui-remix/pull/1

**Comment by char0n** [comment]
Twitter release annoucement: https://twitter.com/vladimirgorej/status/1744659086875005201
LinkedIn release announcement: https://www.linkedin.com/feed/update/urn:li:activity:7150424019777830912/
